/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#454747",
        "surface-tint": "#b8c3ff",
        "error": "#ffb4ab",
        "surface-dim": "#131313",
        "surface-variant": "#353535",
        "on-tertiary": "#00390f",
        "surface-container-highest": "#353535",
        "surface-container-lowest": "#0e0e0e",
        "tertiary": "#60df71",
        "tertiary-fixed-dim": "#60df71",
        "on-primary": "#002388",
        "on-tertiary-fixed-variant": "#00531a",
        "surface": "#131313",
        "on-background": "#e2e2e2",
        "on-tertiary-container": "#c7ffc3",
        "on-secondary-fixed": "#1a1c1c",
        "inverse-on-surface": "#303030",
        "surface-container-high": "#2a2a2a",
        "on-primary-container": "#efefff",
        "on-secondary-fixed-variant": "#454747",
        "on-primary-fixed-variant": "#0035be",
        "secondary-fixed": "#e2e2e2",
        "outline-variant": "#434656",
        "surface-container-low": "#1b1b1b",
        "secondary-fixed-dim": "#c6c6c7",
        "inverse-primary": "#124af0",
        "error-container": "#93000a",
        "on-surface": "#e2e2e2",
        "primary-fixed": "#dde1ff",
        "on-secondary": "#2f3131",
        "on-error-container": "#ffdad6",
        "background": "#131313",
        "primary-container": "#2e5bff",
        "on-surface-variant": "#c4c5d9",
        "inverse-surface": "#e2e2e2",
        "on-error": "#690005",
        "on-tertiary-fixed": "#002106",
        "outline": "#8e90a2",
        "tertiary-container": "#007f2c",
        "primary": "#b8c3ff",
        "on-secondary-container": "#b4b5b5",
        "surface-container": "#1f1f1f",
        "secondary": "#c6c6c7",
        "surface-bright": "#393939",
        "primary-fixed-dim": "#b8c3ff",
        "tertiary-fixed": "#7dfd8a",
        "on-primary-fixed": "#001356"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
